---
# Tasks for prod instance

- name: Ensure Docker is present
  apt:
    pkg:
    - docker.io
    update_cache: yes     

- name: Create a directory for boxfuse war file
  file:
    path: "{{ boxfuse_dir }}/target"
    state: directory
    mode: '0755'

- name: Get boxfuse war file from aws s3
  amazon.aws.aws_s3:
    aws_access_key: "{{ AWS_AK_ID }}"
    aws_secret_key: "{{ AWS_SA_KEY }}"
    region: "{{ AWS_DR }}"
    bucket: "{{ s3bucket }}"
    object: "{{ s3bucket_file }}"
    dest: "{{ boxfuse_dir }}/target/hello-1.0.war"
    mode: get    

- name: Run Tomcat container
  community.docker.docker_container:
    name: boxfuse
    image: tomcat:9.0.20-jre8-alpine
    state: started
    ports:
     - "8080:8080"
    volumes:
      - "{{ boxfuse_dir }}/target:/usr/local/tomcat/webapps"