---
# Tasks for builder instance

- name: Ensure Java and Maven are present
  apt:
    pkg:
    - openjdk-8-jdk
    - maven
    update_cache: yes     

- name: Clone the Boxfuse project
  git:
    repo: "{{ boxfuse_link }}"
    dest: "{{ boxfuse_dir }}"

- name: Build Boxfuse project war
  command: mvn -f "{{ boxfuse_dir }}"/pom.xml clean package

- name: Put boxfuse war file to aws s3
  amazon.aws.aws_s3:
    aws_access_key: "{{ AWS_AK_ID }}"
    aws_secret_key: "{{ AWS_SA_KEY }}"
    region: "{{ AWS_DR }}"
    bucket: "{{ s3bucket }}"
    object: "{{ s3bucket_file }}"
    src: "{{ boxfuse_dir }}"/target/hello-1.0.war
    mode: put